
import { Translation, Project, Service, Testimonial, BlogPost } from './types';
import { LayoutTemplate, Code, TrendingUp, Share2 } from 'lucide-react';

export const translations: { [key: string]: Translation } = {
  es: {
    nav_home: "Inicio",
    nav_services: "Servicios",
    nav_portfolio: "Portafolio",
    nav_about: "Nosotros",
    nav_blog: "Blog",
    nav_contact: "Contacto",
    cta_button: "Solicita presupuesto",
    view_case_study: "Ver caso de estudio",
    read_more: "Leer más",
    home_hero_title: "Diseñamos webs que venden",
    home_hero_subtitle: "En Webora transformamos tu presencia online con diseño, desarrollo, SEO y gestión de redes sociales.",
    home_services_title: "Nuestros Servicios",
    home_services_subtitle: "Soluciones integrales para potenciar tu negocio digital.",
    home_results_title: "Resultados que hablan",
    home_results_subtitle: "Impulsamos el crecimiento con estrategias medibles y efectivas.",
    home_results_metric1_label: "Aumento de Tráfico",
    home_results_metric2_label: "Tasa de Conversión",
    home_results_metric3_label: "Proyectos Entregados",
    home_portfolio_title: "Proyectos Destacados",
    home_portfolio_subtitle: "Creatividad y tecnología en cada entrega.",
    home_testimonials_title: "Lo que dicen nuestros clientes",
    home_testimonials_subtitle: "La confianza es nuestro mayor activo.",
    home_cta_strip_title: "¿Listo para empezar tu proyecto?",
    services_page_title: "Servicios a tu Medida",
    services_page_subtitle: "Desde el concepto hasta el lanzamiento, cubrimos todas tus necesidades digitales.",
    service_title_design: "Diseño Web UI/UX",
    service_desc_design: "Creamos interfaces atractivas y fáciles de usar que convierten visitantes en clientes.",
    service_process_design: "1. Investigación y Estrategia. 2. Wireframing y Prototipado. 3. Diseño Visual y Entrega.",
    service_deliverables_design: "Guía de estilo, prototipos interactivos, archivos de diseño completos.",
    service_title_dev: "Desarrollo Web",
    service_desc_dev: "Webs rápidas, seguras y escalables construidas con las últimas tecnologías.",
    service_process_dev: "1. Planificación Técnica. 2. Desarrollo Frontend y Backend. 3. Pruebas y Despliegue.",
    service_deliverables_dev: "Código fuente, base de datos, documentación técnica.",
    service_title_seo: "Optimización SEO",
    service_desc_seo: "Posicionamos tu web en los primeros resultados de búsqueda para atraer tráfico cualificado.",
    service_process_seo: "1. Auditoría SEO. 2. Optimización On-Page y Off-Page. 3. Monitorización y Reportes.",
    service_deliverables_seo: "Informe de auditoría, plan de palabras clave, reportes de posicionamiento.",
    service_title_social: "Gestión de Redes Sociales",
    service_desc_social: "Construimos y gestionamos tu comunidad online para fortalecer tu marca.",
    service_process_social: "1. Estrategia de Contenidos. 2. Creación y Programación. 3. Análisis de Métricas.",
    service_deliverables_social: "Calendario de contenidos, creatividades, informes de rendimiento.",
    service_process_title: "Nuestro Proceso",
    service_deliverables_title: "Entregables Clave",
    portfolio_page_title: "Nuestro Portafolio",
    portfolio_page_subtitle: "Un vistazo a los desafíos que hemos resuelto y las marcas que hemos impulsado.",
    portfolio_filter_all: "Todos",
    portfolio_filter_web: "Diseño Web",
    portfolio_filter_ecommerce: "E-commerce",
    portfolio_filter_branding: "Branding",
    project_title_1: "TechFlow",
    project_desc_1: "Rediseño completo de la plataforma SaaS para mejorar la experiencia de usuario.",
    project_category_1: "Diseño Web",
    project_title_2: "GreenLeaf",
    project_desc_2: "Tienda online para marca de productos ecológicos, enfocada en la conversión.",
    project_category_2: "E-commerce",
    project_title_3: "InnovateCo",
    project_desc_3: "Identidad de marca y web corporativa para una startup de tecnología.",
    project_category_3: "Branding",
    project_title_4: "DataWise",
    project_desc_4: "Landing page para una herramienta de análisis de datos B2B.",
    project_category_4: "Diseño Web",
    project_title_5: "Artisan",
    project_desc_5: "Plataforma de e-commerce para artesanos locales con pasarela de pago integrada.",
    project_category_5: "E-commerce",
    project_title_6: "Connectify",
    project_desc_6: "Creación de una nueva identidad visual para una app de networking.",
    project_category_6: "Branding",
    about_page_title: "Sobre Webora",
    about_page_subtitle: "Somos un equipo de creativos, estrategas y desarrolladores apasionados por lo digital.",
    about_philosophy_title: "Nuestra Filosofía",
    about_philosophy_text: "Creemos en la colaboración, la transparencia y el ROI. Tu éxito es nuestro éxito. Nos enfocamos en construir relaciones a largo plazo, convirtiéndonos en un socio estratégico para tu crecimiento digital.",
    about_timeline_title: "Nuestra Historia",
    about_timeline_subtitle: "Un viaje de crecimiento e innovación.",
    about_milestone1_year: "2020",
    about_milestone1_title: "Nace Webora",
    about_milestone1_desc: "Fundada con la misión de crear webs que generen resultados reales.",
    about_milestone2_year: "2022",
    about_milestone2_title: "Primeros 50 Proyectos",
    about_milestone2_desc: "Alcanzamos nuestro hito de 50 proyectos exitosos y expandimos el equipo.",
    about_milestone3_year: "2024",
    about_milestone3_title: "Expansión de Servicios",
    about_milestone3_desc: "Incorporamos SEO y Redes Sociales para ofrecer una solución integral.",
    blog_page_title: "Nuestro Blog",
    blog_page_subtitle: "Ideas, tendencias y consejos del mundo del marketing digital y la tecnología.",
    post1_title: "5 claves para un diseño web que convierte",
    post1_excerpt: "Descubre los elementos esenciales que no pueden faltar en tu web para maximizar las conversiones.",
    post2_title: "El futuro del SEO: ¿Qué esperar en 2025?",
    post2_excerpt: "Analizamos las tendencias que marcarán el posicionamiento en buscadores el próximo año.",
    post3_title: "Cómo crear una estrategia de contenidos para redes sociales",
    post3_excerpt: "Una guía paso a paso para planificar, crear y medir el éxito de tus contenidos.",
    post4_title: "React vs. Vue: ¿Qué framework elegir para tu proyecto?",
    post4_excerpt: "Comparamos dos de las tecnologías frontend más populares del momento.",
    contact_page_title: "Hablemos",
    contact_page_subtitle: "Estamos listos para escuchar tu idea. Rellena el formulario o contáctanos directamente.",
    contact_form_name: "Nombre",
    contact_form_email: "Email",
    contact_form_subject: "Asunto",
    contact_form_message: "Mensaje",
    contact_form_send: "Enviar Mensaje",
    contact_form_sending: "Enviando...",
    contact_form_success: "¡Mensaje enviado! Nos pondremos en contacto pronto.",
    contact_info_title: "Información de Contacto",
    contact_info_address: "123 Calle Ficticia, Ciudad Digital, 12345",
    testimonial1_quote: "El equipo de Webora transformó nuestra web. El tráfico ha subido un 200% y las ventas también.",
    testimonial1_company: "CEO de TechFlow",
    testimonial2_quote: "Profesionales, creativos y cumplen los plazos. Su atención al detalle es impecable.",
    testimonial2_company: "Fundadora de GreenLeaf",
    testimonial3_quote: "Desde que gestionan nuestro SEO, nuestra visibilidad online se ha disparado. ¡Totalmente recomendados!",
    testimonial3_company: "CMO de InnovateCo",
    footer_description: "Agencia digital especializada en diseño, desarrollo, SEO y redes sociales.",
    footer_links_title: "Enlaces",
    footer_social_title: "Redes",
    footer_copyright: "© 2024 Webora. Todos los derechos reservados."
  },
  en: {
    nav_home: "Home",
    nav_services: "Services",
    nav_portfolio: "Portfolio",
    nav_about: "About Us",
    nav_blog: "Blog",
    nav_contact: "Contact",
    cta_button: "Request a quote",
    view_case_study: "View Case Study",
    read_more: "Read more",
    home_hero_title: "We design websites that sell",
    home_hero_subtitle: "At Webora, we transform your online presence with design, development, SEO, and social media management.",
    home_services_title: "Our Services",
    home_services_subtitle: "Comprehensive solutions to boost your digital business.",
    home_results_title: "Results that Speak",
    home_results_subtitle: "We drive growth with measurable and effective strategies.",
    home_results_metric1_label: "Traffic Increase",
    home_results_metric2_label: "Conversion Rate",
    home_results_metric3_label: "Projects Delivered",
    home_portfolio_title: "Featured Projects",
    home_portfolio_subtitle: "Creativity and technology in every delivery.",
    home_testimonials_title: "What our clients say",
    home_testimonials_subtitle: "Trust is our greatest asset.",
    home_cta_strip_title: "Ready to start your project?",
    services_page_title: "Customized Services",
    services_page_subtitle: "From concept to launch, we cover all your digital needs.",
    service_title_design: "UI/UX Web Design",
    service_desc_design: "We create attractive and user-friendly interfaces that turn visitors into customers.",
    service_process_design: "1. Research & Strategy. 2. Wireframing & Prototyping. 3. Visual Design & Handoff.",
    service_deliverables_design: "Style guide, interactive prototypes, complete design files.",
    service_title_dev: "Web Development",
    service_desc_dev: "Fast, secure, and scalable websites built with the latest technologies.",
    service_process_dev: "1. Technical Planning. 2. Frontend & Backend Development. 3. Testing & Deployment.",
    service_deliverables_dev: "Source code, database, technical documentation.",
    service_title_seo: "SEO Optimization",
    service_desc_seo: "We position your website at the top of search results to attract qualified traffic.",
    service_process_seo: "1. SEO Audit. 2. On-Page & Off-Page Optimization. 3. Monitoring & Reporting.",
    service_deliverables_seo: "Audit report, keyword plan, ranking reports.",
    service_title_social: "Social Media Management",
    service_desc_social: "We build and manage your online community to strengthen your brand.",
    service_process_social: "1. Content Strategy. 2. Creation & Scheduling. 3. Metrics Analysis.",
    service_deliverables_social: "Content calendar, creatives, performance reports.",
    service_process_title: "Our Process",
    service_deliverables_title: "Key Deliverables",
    portfolio_page_title: "Our Portfolio",
    portfolio_page_subtitle: "A look at the challenges we've solved and the brands we've boosted.",
    portfolio_filter_all: "All",
    portfolio_filter_web: "Web Design",
    portfolio_filter_ecommerce: "E-commerce",
    portfolio_filter_branding: "Branding",
    project_title_1: "TechFlow",
    project_desc_1: "Complete redesign of the SaaS platform to improve user experience.",
    project_category_1: "Web Design",
    project_title_2: "GreenLeaf",
    project_desc_2: "E-commerce store for an organic products brand, focused on conversion.",
    project_category_2: "E-commerce",
    project_title_3: "InnovateCo",
    project_desc_3: "Brand identity and corporate website for a technology startup.",
    project_category_3: "Branding",
    project_title_4: "DataWise",
    project_desc_4: "Landing page for a B2B data analysis tool.",
    project_category_4: "Web Design",
    project_title_5: "Artisan",
    project_desc_5: "E-commerce platform for local artisans with an integrated payment gateway.",
    project_category_5: "E-commerce",
    project_title_6: "Connectify",
    project_desc_6: "Creation of a new visual identity for a networking app.",
    project_category_6: "Branding",
    about_page_title: "About Webora",
    about_page_subtitle: "We are a team of creatives, strategists, and developers passionate about digital.",
    about_philosophy_title: "Our Philosophy",
    about_philosophy_text: "We believe in collaboration, transparency, and ROI. Your success is our success. We focus on building long-term relationships, becoming a strategic partner for your digital growth.",
    about_timeline_title: "Our History",
    about_timeline_subtitle: "A journey of growth and innovation.",
    about_milestone1_year: "2020",
    about_milestone1_title: "Webora is Born",
    about_milestone1_desc: "Founded with the mission to create websites that generate real results.",
    about_milestone2_year: "2022",
    about_milestone2_title: "First 50 Projects",
    about_milestone2_desc: "We reached our milestone of 50 successful projects and expanded the team.",
    about_milestone3_year: "2024",
    about_milestone3_title: "Service Expansion",
    about_milestone3_desc: "We incorporated SEO and Social Media to offer a comprehensive solution.",
    blog_page_title: "Our Blog",
    blog_page_subtitle: "Ideas, trends, and tips from the world of digital marketing and technology.",
    post1_title: "5 keys to a web design that converts",
    post1_excerpt: "Discover the essential elements your website must have to maximize conversions.",
    post2_title: "The future of SEO: What to expect in 2025?",
    post2_excerpt: "We analyze the trends that will define search engine positioning next year.",
    post3_title: "How to create a content strategy for social media",
    post3_excerpt: "A step-by-step guide to planning, creating, and measuring the success of your content.",
    post4_title: "React vs. Vue: Which framework to choose for your project?",
    post4_excerpt: "We compare two of the most popular frontend technologies of the moment.",
    contact_page_title: "Let's Talk",
    contact_page_subtitle: "We are ready to hear your idea. Fill out the form or contact us directly.",
    contact_form_name: "Name",
    contact_form_email: "Email",
    contact_form_subject: "Subject",
    contact_form_message: "Message",
    contact_form_send: "Send Message",
    contact_form_sending: "Sending...",
    contact_form_success: "Message sent! We will be in touch soon.",
    contact_info_title: "Contact Information",
    contact_info_address: "123 Fictional Street, Digital City, 12345",
    testimonial1_quote: "The Webora team transformed our website. Traffic is up 200%, and so are sales.",
    testimonial1_company: "CEO of TechFlow",
    testimonial2_quote: "Professional, creative, and they meet deadlines. Their attention to detail is impeccable.",
    testimonial2_company: "Founder of GreenLeaf",
    testimonial3_quote: "Since they started managing our SEO, our online visibility has skyrocketed. Highly recommended!",
    testimonial3_company: "CMO of InnovateCo",
    footer_description: "Digital agency specializing in design, development, SEO, and social media.",
    footer_links_title: "Links",
    footer_social_title: "Social",
    footer_copyright: "© 2024 Webora. All rights reserved."
  }
};

export const MOCK_PROJECTS: Project[] = [
  { id: 1, titleKey: 'project_title_1', categoryKey: 'portfolio_filter_web', image: 'https://picsum.photos/seed/project1/600/400', descriptionKey: 'project_desc_1' },
  { id: 2, titleKey: 'project_title_2', categoryKey: 'portfolio_filter_ecommerce', image: 'https://picsum.photos/seed/project2/600/400', descriptionKey: 'project_desc_2' },
  { id: 3, titleKey: 'project_title_3', categoryKey: 'portfolio_filter_branding', image: 'https://picsum.photos/seed/project3/600/400', descriptionKey: 'project_desc_3' },
  { id: 4, titleKey: 'project_title_4', categoryKey: 'portfolio_filter_web', image: 'https://picsum.photos/seed/project4/600/400', descriptionKey: 'project_desc_4' },
  { id: 5, titleKey: 'project_title_5', categoryKey: 'portfolio_filter_ecommerce', image: 'https://picsum.photos/seed/project5/600/400', descriptionKey: 'project_desc_5' },
  { id: 6, titleKey: 'project_title_6', categoryKey: 'portfolio_filter_branding', image: 'https://picsum.photos/seed/project6/600/400', descriptionKey: 'project_desc_6' },
];

export const MOCK_SERVICES: Service[] = [
  { id: 1, titleKey: 'service_title_design', descriptionKey: 'service_desc_design', icon: LayoutTemplate, details: { processKey: 'service_process_design', deliverablesKey: 'service_deliverables_design' } },
  { id: 2, titleKey: 'service_title_dev', descriptionKey: 'service_desc_dev', icon: Code, details: { processKey: 'service_process_dev', deliverablesKey: 'service_deliverables_dev' } },
  { id: 3, titleKey: 'service_title_seo', descriptionKey: 'service_desc_seo', icon: TrendingUp, details: { processKey: 'service_process_seo', deliverablesKey: 'service_deliverables_seo' } },
  { id: 4, titleKey: 'service_title_social', descriptionKey: 'service_desc_social', icon: Share2, details: { processKey: 'service_process_social', deliverablesKey: 'service_deliverables_social' } },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
    { id: 1, quoteKey: 'testimonial1_quote', name: 'Alex Johnson', companyKey: 'testimonial1_company' },
    { id: 2, quoteKey: 'testimonial2_quote', name: 'Maria Garcia', companyKey: 'testimonial2_company' },
    { id: 3, quoteKey: 'testimonial3_quote', name: 'David Chen', companyKey: 'testimonial3_company' },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
    { id: 1, titleKey: 'post1_title', excerptKey: 'post1_excerpt', date: 'October 26, 2024', image: 'https://picsum.photos/seed/blog1/600/400' },
    { id: 2, titleKey: 'post2_title', excerptKey: 'post2_excerpt', date: 'October 22, 2024', image: 'https://picsum.photos/seed/blog2/600/400' },
    { id: 3, titleKey: 'post3_title', excerptKey: 'post3_excerpt', date: 'October 18, 2024', image: 'https://picsum.photos/seed/blog3/600/400' },
    { id: 4, titleKey: 'post4_title', excerptKey: 'post4_excerpt', date: 'October 15, 2024', image: 'https://picsum.photos/seed/blog4/600/400' },
];
