
import { Translation, Project, Service, Testimonial, BlogPost } from './types';
import { LayoutTemplate, Code, TrendingUp, Share2 } from 'lucide-react';

// Importar imágenes directamente
import germanImage from './img/proyectos/german.webp';
import mambaImage from './img/proyectos/mamba2.webp';
import queleregaloImage from './img/proyectos/queleregalo.webp';
import smilehotdogImage from './img/proyectos/smilehotdog.webp';
import smilesmashImage from './img/proyectos/smilesmash.webp';

export const translations: { [key: string]: Translation } = {
  es: {
    nav_home: "Inicio",
    nav_services: "Servicios",
    nav_portfolio: "Portafolio",
    nav_about: "Nosotros",
    nav_blog: "Blog",
    nav_contact: "Contacto",
    cta_button: "Solicita presupuesto",
    view_case_study: "Ver",
    read_more: "Leer más",
    home_hero_title: "Diseñamos webs que venden",
    home_hero_subtitle: "En Webora transformamos tu presencia online con diseño, desarrollo, SEO y gestión de redes sociales.",
    home_services_title: "Nuestros Servicios",
    home_services_subtitle: "Soluciones integrales para potenciar tu negocio digital.",
    home_results_title: "Resultados que hablan",
    home_results_subtitle: "Impulsamos el crecimiento con estrategias medibles y efectivas.",
    home_results_metric1_label: "Aumento de Tráfico",
    home_results_metric2_label: "Tasa de Conversión",
    home_results_metric3_label: "Proyectos Entregados",
    home_portfolio_title: "Proyectos Destacados",
    home_portfolio_subtitle: "Creatividad y tecnología en cada entrega.",
    home_testimonials_title: "Lo que dicen nuestros clientes",
    home_testimonials_subtitle: "La confianza es nuestro mayor activo.",
    home_cta_strip_title: "¿Listo para empezar tu proyecto?",
    home_cta_subtitle: "Transforma tu visión en realidad digital. Nuestro equipo está listo para crear algo extraordinario contigo.",
    home_cta_stats_projects: "50+",
    home_cta_stats_projects_label: "Proyectos Exitosos",
    home_cta_stats_satisfaction: "98%",
    home_cta_stats_satisfaction_label: "Clientes Satisfechos",
    home_cta_stats_support: "24/7",
    home_cta_stats_support_label: "Soporte Disponible",
    home_cta_button_portfolio: "Ver Portafolio",
    home_cta_trust_text: "Sin compromisos • Respuesta en 24h • Presupuesto personalizado",
    services_page_title: "Servicios a tu Medida",
    services_page_subtitle: "Desde el concepto hasta el lanzamiento, cubrimos todas tus necesidades digitales.",
    service_title_design: "Diseño Web UI/UX",
    service_desc_design: "Creamos interfaces atractivas y fáciles de usar que convierten visitantes en clientes.",
    service_process_design: "1. Investigación y Estrategia.\n2. Wireframing y Prototipado.\n3. Diseño Visual y Entrega.",
    service_deliverables_design: "Guía de estilo, prototipos interactivos, archivos de diseño completos.",
    service_title_dev: "Desarrollo Web",
    service_desc_dev: "Webs rápidas, seguras y escalables construidas con las últimas tecnologías.",
    service_process_dev: "1. Planificación Técnica.\n2. Desarrollo Frontend y Backend.\n3. Pruebas y Despliegue.",
    service_deliverables_dev: "Código fuente, base de datos, documentación técnica.",
    service_title_seo: "Optimización SEO",
    service_desc_seo: "Posicionamos tu web en los primeros resultados de búsqueda para atraer tráfico cualificado.",
    service_process_seo: "1. Auditoría SEO.\n2. Optimización On-Page y Off-Page.\n3. Monitorización y Reportes.",
    service_deliverables_seo: "Informe de auditoría, plan de palabras clave, reportes de posicionamiento.",
    service_title_social: "Gestión de Redes Sociales",
    service_desc_social: "Construimos y gestionamos tu comunidad online para fortalecer tu marca.",
    service_process_social: "1. Estrategia de Contenidos.\n2. Creación y Programación.\n3. Análisis de Métricas.",
    service_deliverables_social: "Calendario de contenidos, creatividades, informes de rendimiento.",
    service_process_title: "Nuestro Proceso",
    service_deliverables_title: "Entregables Clave",
    service_cta_title: "¿Necesitas algo más específico?",
    service_cta_description: "Cada proyecto es único. Si tienes necesidades especiales o quieres personalizar alguno de nuestros servicios, estamos aquí para ayudarte a crear la solución perfecta.",
    service_cta_button: "Hablemos de tu proyecto",
    portfolio_page_title: "Nuestro Portafolio",
    portfolio_page_subtitle: "Un vistazo a los desafíos que hemos resuelto y las marcas que hemos impulsado.",
    portfolio_filter_all: "Todos",
    portfolio_filter_web: "Diseño Web",
    portfolio_filter_ecommerce: "E-commerce",
    portfolio_filter_ai: "IA",
    project_title_1: "German Fotografía",
    project_desc_1: "Sitio web profesional para estudio de fotografía con galería de portafolio y sistema de reservas.",
    project_category_1: "Diseño Web",
    project_title_2: "Mamba Automóvil",
    project_desc_2: "Plataforma web para concesionario de automóviles con catálogo de vehículos y formularios de contacto.",
    project_category_2: "Diseño Web",
    project_title_3: "Smile Hot Dog",
    project_desc_3: "Sitio web para restaurante de hot dogs con menú digital y sistema de pedidos online.",
    project_category_3: "Diseño Web",
    project_title_4: "Smile Smash Burger",
    project_desc_4: "Plataforma web para restaurante de hamburguesas con menú interactivo y reservas online.",
    project_category_4: "Diseño Web",
    project_title_5: "Que Le Regalo",
    project_desc_5: "Plataforma web con IA integrada para recomendación personalizada de regalos basada en preferencias y gustos.",
    project_category_5: "IA",
    project_title_6: "TechFlow",
    project_desc_6: "Rediseño completo de la plataforma SaaS para mejorar la experiencia de usuario.",
    project_category_6: "Diseño Web",
    about_page_title: "Sobre Webora",
    about_page_subtitle: "Somos un equipo de creativos, estrategas y desarrolladores apasionados por lo digital.",
    about_philosophy_title: "Nuestra Filosofía",
    about_philosophy_text: "Creemos en la colaboración, la transparencia y el ROI. Tu éxito es nuestro éxito. Nos enfocamos en construir relaciones a largo plazo, convirtiéndonos en un socio estratégico para tu crecimiento digital.",
    about_timeline_title: "Nuestra Historia",
    about_timeline_subtitle: "Un viaje de crecimiento e innovación.",
    about_milestone1_year: "2020",
    about_milestone1_title: "Nace Webora",
    about_milestone1_desc: "Fundada con la misión de crear webs que generen resultados reales.",
    about_milestone2_year: "2022",
    about_milestone2_title: "Primeros 50 Proyectos",
    about_milestone2_desc: "Alcanzamos nuestro hito de 50 proyectos exitosos y expandimos el equipo.",
    about_milestone3_year: "2025",
    about_milestone3_title: "Expansión de Servicios",
    about_milestone3_desc: "Incorporamos SEO y Redes Sociales para ofrecer una solución integral.",
    about_story_title: "Sé lo que es tener algo valioso que ofrecer y que nadie lo vea.",
    about_story_paragraph1: "Recuerdo a un cliente que tenía un negocio increíble, pero su web era tan anticuada que la gente no confiaba en él.",
    about_story_paragraph2: "Rediseñamos su página y en un mes ya estaba recibiendo más consultas que nunca. Ahí entendí que una web no es solo algo bonito, es la clave para hacer crecer un negocio.",
    about_story_paragraph3: "Soy Juan Paulino, fundador de nxerio. Durante más de 7 años he trabajado con negocios que, como el tuyo, necesitaban dar el salto digital.",
    about_story_paragraph4: "En nxerio no solo creamos webs, creamos herramientas que trabajan para ti. Si sientes que tu negocio merece más, estamos aquí para hacerlo realidad.",
    
    // Sección de texto motivacional
    about_motivational_title: "¡Hola!",
    about_motivational_paragraph1: "Si estás aquí, es muy probable que estés buscando transformar una idea brillante en un servicio o producto digital que eleve tu negocio a nuevas cotas.",
    about_motivational_paragraph2: "Entendemos que confiar algo tan importante en un tercero, puede resultar una decisión complicada. Tal vez has tenido experiencias pasadas que no salieron como esperabas, o quizás simplemente te sientes abrumado ante el reto tecnológico. No te preocupes, estás en el lugar perfecto.",
    about_motivational_paragraph3: "Desde el momento en que decides trabajar con nosotros, tu visión se convierte en nuestra misión. Olvídate de posibles tensiones al colaborar con otros equipos. No solo aspiramos a cumplir tus expectativas, vamos a superarlas. Y además, te garantizamos que vas a disfrutar del PROCESO.",
    about_motivational_paragraph4: "Hemos diseñado meticulosamente un proceso de trabajo sistematizado, para garantizar: claridad, comunicación honesta y efectiva, y cumplimiento de plazos, presupuesto y objetivos. Con nosotros, el proceso es tan satisfactorio como el producto final.",
    about_motivational_question: "¿Estás preparado?",
    about_motivational_paragraph5: "Desde nuestro primer contacto, vamos a centrarnos en entender al detalle tus necesidades para ofrecerte la mejor solución.",
    about_motivational_cta: "Hagamos magia juntos. Hablemos ;)",
    
    // Sección de proceso
    home_process_title: "¿Cómo lo hacemos?",
    home_process_subtitle: "Fácil de empezar y ágil hasta el final. Mantendremos las comunicaciones asíncronas y reduciremos las reuniones al mínimo, por tu bien y por el mío.",
    home_process_step1_title: "Solicitud",
    home_process_step1_desc: "Háblanos de tu proyecto",
    home_process_step2_title: "Estimación",
    home_process_step2_desc: "Obtén tu presupuesto",
    home_process_step3_title: "Aprobación",
    home_process_step3_desc: "Ok, envíanos los detalles",
    home_process_step4_title: "Desarrollo",
    home_process_step4_desc: "Trabajamos tu proyecto",
    home_process_step5_title: "Entrega",
    home_process_step5_desc: "Lanza tu proyecto",
    blog_page_title: "Nuestro Blog",
    blog_page_subtitle: "Ideas, tendencias y consejos del mundo del marketing digital y la tecnología.",
    post1_title: "5 claves para un diseño web que convierte",
    post1_excerpt: "Descubre los elementos esenciales que no pueden faltar en tu web para maximizar las conversiones.",
    post2_title: "El futuro del SEO: ¿Qué esperar en 2025?",
    post2_excerpt: "Analizamos las tendencias que marcarán el posicionamiento en buscadores el próximo año.",
    post3_title: "Cómo crear una estrategia de contenidos para redes sociales",
    post3_excerpt: "Una guía paso a paso para planificar, crear y medir el éxito de tus contenidos.",
    post4_title: "React vs. Vue: ¿Qué framework elegir para tu proyecto?",
    post4_excerpt: "Comparamos dos de las tecnologías frontend más populares del momento.",
    contact_page_title: "Hablemos",
    contact_page_subtitle: "Estamos listos para escuchar tu idea. Rellena el formulario o contáctanos directamente.",
    contact_form_name: "Nombre",
    contact_form_email: "Email",
    contact_form_subject: "Asunto",
    contact_form_message: "Mensaje",
    contact_form_send: "Enviar Mensaje",
    contact_form_sending: "Enviando...",
    contact_form_success: "¡Mensaje enviado! Nos pondremos en contacto pronto.",
    contact_info_title: "Información de Contacto",
    contact_info_address: "123 Calle Ficticia, Ciudad Digital, 12345",
    testimonial1_quote: "El equipo de Webora transformó nuestra web. El tráfico ha subido un 200% y las ventas también.",
    testimonial1_company: "Dueño de Smile Smash Burger",
    testimonial3_quote: "Profesionales, creativos y cumplen los plazos. Su atención al detalle es impecable.",
    testimonial2_company: "Dueño de Mamba Automóvil",
    testimonial2_quote: "Desde que gestionan nuestro SEO, nuestra visibilidad online se ha disparado. ¡Totalmente recomendados!",
    testimonial3_company: "German Fotografía",
    footer_description: "Agencia digital especializada en diseño, desarrollo, SEO y redes sociales.",
    footer_links_title: "Enlaces",
    footer_social_title: "Redes",
    footer_copyright: "© 2025 Webora. Todos los derechos reservados.",
    
    // Tags para TagsPhysics
    tag_fluid_animations: "Animaciones fluidas",
    tag_design: "Diseño",
    tag_gsap: "G-sap",
    tag_startup: "Startup",
    tag_backend: "Backend",
    tag_framer: "Framer",
    tag_animations: "Animaciones",
    tag_vue: "Vue",
    tag_saas: "SAAS",
    tag_web_development: "Desarrollo web",
    tag_react: "React",
    tag_typescript: "TypeScript",
    tag_tailwind: "Tailwind",
    tag_nodejs: "Node.js",
    tag_api: "API",
    tag_seo: "SEO",
    tag_marketing: "Marketing",
    tag_branding: "Branding",
    tag_wordpress: "Wordpress",
    tag_ecommerce: "E-commerce",
    tag_mobile: "Mobile"
  },
  en: {
    nav_home: "Home",
    nav_services: "Services",
    nav_portfolio: "Portfolio",
    nav_about: "About Us",
    nav_blog: "Blog",
    nav_contact: "Contact",
    cta_button: "Request a quote",
    view_case_study: "View",
    read_more: "Read more",
    home_hero_title: "We design websites that sell",
    home_hero_subtitle: "At Webora, we transform your online presence with design, development, SEO, and social media management.",
    home_services_title: "Our Services",
    home_services_subtitle: "Comprehensive solutions to boost your digital business.",
    home_results_title: "Results that Speak",
    home_results_subtitle: "We drive growth with measurable and effective strategies.",
    home_results_metric1_label: "Traffic Increase",
    home_results_metric2_label: "Conversion Rate",
    home_results_metric3_label: "Projects Delivered",
    home_portfolio_title: "Featured Projects",
    home_portfolio_subtitle: "Creativity and technology in every delivery.",
    home_testimonials_title: "What our clients say",
    home_testimonials_subtitle: "Trust is our greatest asset.",
    home_cta_strip_title: "Ready to start your project?",
    home_cta_subtitle: "Transform your vision into digital reality. Our team is ready to create something extraordinary with you.",
    home_cta_stats_projects: "50+",
    home_cta_stats_projects_label: "Successful Projects",
    home_cta_stats_satisfaction: "98%",
    home_cta_stats_satisfaction_label: "Satisfied Clients",
    home_cta_stats_support: "24/7",
    home_cta_stats_support_label: "Available Support",
    home_cta_button_portfolio: "View Portfolio",
    home_cta_trust_text: "No commitments • 24h response • Personalized budget",
    services_page_title: "Customized Services",
    services_page_subtitle: "From concept to launch, we cover all your digital needs.",
    service_title_design: "UI/UX Web Design",
    service_desc_design: "We create attractive and user-friendly interfaces that turn visitors into customers.",
    service_process_design: "1. Research & Strategy.\n2. Wireframing & Prototyping.\n3. Visual Design & Handoff.",
    service_deliverables_design: "Style guide, interactive prototypes, complete design files.",
    service_title_dev: "Web Development",
    service_desc_dev: "Fast, secure, and scalable websites built with the latest technologies.",
    service_process_dev: "1. Technical Planning.\n2. Frontend & Backend Development.\n3. Testing & Deployment.",
    service_deliverables_dev: "Source code, database, technical documentation.",
    service_title_seo: "SEO Optimization",
    service_desc_seo: "We position your website at the top of search results to attract qualified traffic.",
    service_process_seo: "1. SEO Audit.\n2. On-Page & Off-Page Optimization.\n3. Monitoring & Reporting.",
    service_deliverables_seo: "Audit report, keyword plan, ranking reports.",
    service_title_social: "Social Media Management",
    service_desc_social: "We build and manage your online community to strengthen your brand.",
    service_process_social: "1. Content Strategy.\n2. Creation & Scheduling.\n3. Metrics Analysis.",
    service_deliverables_social: "Content calendar, creatives, performance reports.",
    service_process_title: "Our Process",
    service_deliverables_title: "Key Deliverables",
    service_cta_title: "Do you need something more specific?",
    service_cta_description: "Every project is unique. If you have special needs or want to customize any of our services, we are here to help you create the perfect solution.",
    service_cta_button: "Let's talk about your project",
    portfolio_page_title: "Our Portfolio",
    portfolio_page_subtitle: "A look at the challenges we've solved and the brands we've boosted.",
    portfolio_filter_all: "All",
    portfolio_filter_web: "Web Design",
    portfolio_filter_ecommerce: "E-commerce",
    portfolio_filter_ai: "AI",
    project_title_1: "German Photography",
    project_desc_1: "Professional website for photography studio with portfolio gallery and booking system.",
    project_category_1: "Web Design",
    project_title_2: "Mamba Automobile",
    project_desc_2: "Web platform for automobile dealership with vehicle catalog and contact forms.",
    project_category_2: "Web Design",
    project_title_3: "Smile Hot Dog",
    project_desc_3: "Website for hot dog restaurant with digital menu and online ordering system.",
    project_category_3: "Web Design",
    project_title_4: "Smile Smash Burger",
    project_desc_4: "Web platform for burger restaurant with interactive menu and online reservations.",
    project_category_4: "Web Design",
    project_title_5: "Que Le Regalo",
    project_desc_5: "Web platform with integrated AI for personalized gift recommendations based on preferences and tastes.",
    project_category_5: "AI",
    project_title_6: "TechFlow",
    project_desc_6: "Complete redesign of the SaaS platform to improve user experience.",
    project_category_6: "Web Design",
    about_page_title: "About Webora",
    about_page_subtitle: "We are a team of creatives, strategists, and developers passionate about digital.",
    about_philosophy_title: "Our Philosophy",
    about_philosophy_text: "We believe in collaboration, transparency, and ROI. Your success is our success. We focus on building long-term relationships, becoming a strategic partner for your digital growth.",
    about_timeline_title: "Our History",
    about_timeline_subtitle: "A journey of growth and innovation.",
    about_milestone1_year: "2020",
    about_milestone1_title: "Webora is Born",
    about_milestone1_desc: "Founded with the mission to create websites that generate real results.",
    about_milestone2_year: "2022",
    about_milestone2_title: "First 50 Projects",
    about_milestone2_desc: "We reached our milestone of 50 successful projects and expanded the team.",
    about_milestone3_year: "2025",
    about_milestone3_title: "Service Expansion",
    about_milestone3_desc: "We incorporated SEO and Social Media to offer a comprehensive solution.",
    about_story_title: "I know what it's like to have something valuable to offer and no one sees it.",
    about_story_paragraph1: "I remember a client who had an incredible business, but their website was so outdated that people didn't trust them.",
    about_story_paragraph2: "We redesigned their page and within a month they were already receiving more inquiries than ever. That's when I understood that a website isn't just something pretty, it's the key to growing a business.",
    about_story_paragraph3: "I'm Juan Paulino, founder of nxerio. For more than 7 years I have worked with businesses that, like yours, needed to make the digital leap.",
    about_story_paragraph4: "At nxerio we don't just create websites, we create tools that work for you. If you feel your business deserves more, we are here to make it happen.",
    
    // Motivational text section
    about_motivational_title: "Hello!",
    about_motivational_paragraph1: "If you're here, it's very likely that you're looking to transform a brilliant idea into a digital service or product that elevates your business to new heights.",
    about_motivational_paragraph2: "We understand that trusting something so important to a third party can be a complicated decision. Maybe you've had past experiences that didn't turn out as expected, or perhaps you simply feel overwhelmed by the technological challenge. Don't worry, you're in the perfect place.",
    about_motivational_paragraph3: "From the moment you decide to work with us, your vision becomes our mission. Forget about possible tensions when collaborating with other teams. We don't just aspire to meet your expectations, we're going to exceed them. And furthermore, we guarantee that you're going to enjoy the PROCESS.",
    about_motivational_paragraph4: "We have meticulously designed a systematized work process to guarantee: clarity, honest and effective communication, and compliance with deadlines, budget, and objectives. With us, the process is as satisfying as the final product.",
    about_motivational_question: "Are you ready?",
    about_motivational_paragraph5: "From our first contact, we will focus on understanding your needs in detail to offer you the best solution.",
    about_motivational_cta: "Let's make magic together. Let's talk ;)",
    
    // Process section
    home_process_title: "How do we do it?",
    home_process_subtitle: "Easy to start and agile until the end. We will maintain asynchronous communications and reduce meetings to a minimum, for your benefit and mine.",
    home_process_step1_title: "Request",
    home_process_step1_desc: "Tell us about your project",
    home_process_step2_title: "Estimation",
    home_process_step2_desc: "Get your quote",
    home_process_step3_title: "Approval",
    home_process_step3_desc: "Ok, send us the details",
    home_process_step4_title: "Development",
    home_process_step4_desc: "We work on your project",
    home_process_step5_title: "Delivery",
    home_process_step5_desc: "Launch your project",
    blog_page_title: "Our Blog",
    blog_page_subtitle: "Ideas, trends, and tips from the world of digital marketing and technology.",
    post1_title: "5 keys to a web design that converts",
    post1_excerpt: "Discover the essential elements your website must have to maximize conversions.",
    post2_title: "The future of SEO: What to expect in 2025?",
    post2_excerpt: "We analyze the trends that will define search engine positioning next year.",
    post3_title: "How to create a content strategy for social media",
    post3_excerpt: "A step-by-step guide to planning, creating, and measuring the success of your content.",
    post4_title: "React vs. Vue: Which framework to choose for your project?",
    post4_excerpt: "We compare two of the most popular frontend technologies of the moment.",
    contact_page_title: "Let's Talk",
    contact_page_subtitle: "We are ready to hear your idea. Fill out the form or contact us directly.",
    contact_form_name: "Name",
    contact_form_email: "Email",
    contact_form_subject: "Subject",
    contact_form_message: "Message",
    contact_form_send: "Send Message",
    contact_form_sending: "Sending...",
    contact_form_success: "Message sent! We will be in touch soon.",
    contact_info_title: "Contact Information",
    contact_info_address: "123 Fictional Street, Digital City, 12345",
    testimonial1_quote: "The Webora team transformed our website. Traffic is up 200%, and so are sales.",
    testimonial1_company: "Owner of Smile Smash Burger",
    testimonial3_quote: "Professional, creative, and they meet deadlines. Their attention to detail is impeccable.",
    testimonial2_company: "Owner of Mamba Automóvil",
    testimonial2_quote: "Since they started managing our SEO, our online visibility has skyrocketed. Highly recommended!",
    testimonial3_company: "German Fotografía",
    footer_description: "Digital agency specializing in design, development, SEO, and social media.",
    footer_links_title: "Links",
    footer_social_title: "Social",
    footer_copyright: "© 2025 Webora. All rights reserved.",
    
    // Tags para TagsPhysics
    tag_fluid_animations: "Fluid Animations",
    tag_design: "Design",
    tag_gsap: "G-sap",
    tag_startup: "Startup",
    tag_backend: "Backend",
    tag_framer: "Framer",
    tag_animations: "Animations",
    tag_vue: "Vue",
    tag_saas: "SAAS",
    tag_web_development: "Web Development",
    tag_react: "React",
    tag_typescript: "TypeScript",
    tag_tailwind: "Tailwind",
    tag_nodejs: "Node.js",
    tag_api: "API",
    tag_seo: "SEO",
    tag_marketing: "Marketing",
    tag_branding: "Branding",
    tag_wordpress: "Wordpress",
    tag_ecommerce: "E-commerce",
    tag_mobile: "Mobile"
  }
};

export const MOCK_PROJECTS: Project[] = [
  { id: 1, titleKey: 'project_title_1', categoryKey: 'portfolio_filter_web', image: germanImage, descriptionKey: 'project_desc_1', url: 'https://germannoriega.vercel.app/' },
  { id: 2, titleKey: 'project_title_4', categoryKey: 'portfolio_filter_web', image: smilesmashImage, descriptionKey: 'project_desc_4', url: 'https://www.smilesmashburger.com/' },
  { id: 3, titleKey: 'project_title_3', categoryKey: 'portfolio_filter_web', image: smilehotdogImage, descriptionKey: 'project_desc_3', url: 'https://www.smilehotdog.es/' },
  { id: 4, titleKey: 'project_title_2', categoryKey: 'portfolio_filter_web', image: mambaImage, descriptionKey: 'project_desc_2', url: 'https://comet-x9-orb.resiz.es/' },
  { id: 5, titleKey: 'project_title_5', categoryKey: 'portfolio_filter_ai', image: queleregaloImage, descriptionKey: 'project_desc_5', url: 'https://queleregalo.es' },
  // { id: 6, titleKey: 'project_title_6', categoryKey: 'portfolio_filter_web', image: 'https://picsum.photos/seed/project6/600/400', descriptionKey: 'project_desc_6' },
];

export const MOCK_SERVICES: Service[] = [
  { id: 1, titleKey: 'service_title_design', descriptionKey: 'service_desc_design', icon: LayoutTemplate, details: { processKey: 'service_process_design', deliverablesKey: 'service_deliverables_design' } },
  { id: 2, titleKey: 'service_title_dev', descriptionKey: 'service_desc_dev', icon: Code, details: { processKey: 'service_process_dev', deliverablesKey: 'service_deliverables_dev' } },
  { id: 3, titleKey: 'service_title_seo', descriptionKey: 'service_desc_seo', icon: TrendingUp, details: { processKey: 'service_process_seo', deliverablesKey: 'service_deliverables_seo' } },
  { id: 4, titleKey: 'service_title_social', descriptionKey: 'service_desc_social', icon: Share2, details: { processKey: 'service_process_social', deliverablesKey: 'service_deliverables_social' } },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
    { id: 1, quoteKey: 'testimonial1_quote', name: 'Pedro Mendez', companyKey: 'testimonial1_company' },
    { id: 2, quoteKey: 'testimonial2_quote', name: 'Laura Blanco', companyKey: 'testimonial2_company' },
    { id: 3, quoteKey: 'testimonial3_quote', name: 'German Suarez Noriega', companyKey: 'testimonial3_company' },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
    { id: 1, titleKey: 'post1_title', excerptKey: 'post1_excerpt', date: 'October 26, 2024', image: 'https://picsum.photos/seed/blog1/600/400' },
    { id: 2, titleKey: 'post2_title', excerptKey: 'post2_excerpt', date: 'October 22, 2024', image: 'https://picsum.photos/seed/blog2/600/400' },
    { id: 3, titleKey: 'post3_title', excerptKey: 'post3_excerpt', date: 'October 18, 2024', image: 'https://picsum.photos/seed/blog3/600/400' },
    { id: 4, titleKey: 'post4_title', excerptKey: 'post4_excerpt', date: 'October 15, 2024', image: 'https://picsum.photos/seed/blog4/600/400' },
];
